In [1]:
import numpy as np

In [7]:
a = np.matrix('1 23 23; 4 5 6')
print a
print type(a)

[[ 1 23 23]
 [ 4  5  6]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [3]:
b = np.matrix('2 3 4; 5 6 7')

In [4]:
temp = np.multiply(a,b)
print(temp)

[[ 2 69 92]
 [20 30 42]]


In [6]:
c = np.asarray(a)
print c
print type(c)

[[ 1 23 23]
 [ 4  5  6]]
<type 'numpy.ndarray'>


In [8]:
print a.T

[[ 1  4]
 [23  5]
 [23  6]]


In [9]:
print a*a.T

[[1059  257]
 [ 257   77]]


In [12]:
print a.getT()

[[ 1  4]
 [23  5]
 [23  6]]


In [13]:
a.getT()

matrix([[ 1,  4],
        [23,  5],
        [23,  6]])